/*
 * iosFonts,myFonts,allFonts (well... a lot)
 *
 * iOS 7 fonts
 * http://roadfiresoftware.com/2013/09/fonts-in-ios-7/
 * http://www.whatsyourdigitaliq.com/fonts-available-in-various-versions-of-ios/
 */
var iosFonts = [
"AcademyEngravedLetPlain",
"AlNile",
"AlNile-Bold",
"AmericanTypewriter",
"AmericanTypewriter-Bold",
"AmericanTypewriter-Condensed",
"AmericanTypewriter-CondensedBold",
"AmericanTypewriter-CondensedLight",
"AmericanTypewriter-Light",
"AppleColorEmoji",
"AppleSDGothicNeo-Bold",
"AppleSDGothicNeo-Light",
"AppleSDGothicNeo-Medium",
"AppleSDGothicNeo-Regular",
"AppleSDGothicNeo-SemiBold",
"AppleSDGothicNeo-Thin",
"Arial",
"Arial-BoldItalicMT",
"Arial-BoldMT",
"Arial-ItalicMT",
"ArialMT",
"ArialHebrew",
"ArialHebrew-Bold",
"ArialHebrew-Light",
"ArialRoundedMTBold",
"Avenir-Black",
"Avenir-BlackOblique",
"Avenir-Book",
"Avenir-BookOblique",
"Avenir-Heavy",
"Avenir-HeavyOblique",
"Avenir-Light",
"Avenir-LightOblique",
"Avenir-Medium",
"Avenir-MediumOblique",
"Avenir-Oblique",
"Avenir-Roman",
"AvenirNext-Bold",
"AvenirNext-BoldItalic",
"AvenirNext-DemiBold",
"AvenirNext-DemiBoldItalic",
"AvenirNext-Heavy",
"AvenirNext-HeavyItalic",
"AvenirNext-Italic",
"AvenirNext-Medium",
"AvenirNext-MediumItalic",
"AvenirNext-Regular",
"AvenirNext-UltraLight",
"AvenirNext-UltraLightItalic",
"AvenirNextCondensed-Bold",
"AvenirNextCondensed-BoldItalic",
"AvenirNextCondensed-DemiBold",
"AvenirNextCondensed-DemiBoldItalic",
"AvenirNextCondensed-Heavy",
"AvenirNextCondensed-HeavyItalic",
"AvenirNextCondensed-Italic",
"AvenirNextCondensed-Medium",
"AvenirNextCondensed-MediumItalic",
"AvenirNextCondensed-Regular",
"AvenirNextCondensed-UltraLight",
"AvenirNextCondensed-UltraLightItalic",
"BanglaSangamMN",
"BanglaSangamMN-Bold",
"Baskerville",
"Baskerville-Bold",
"Baskerville-BoldItalic",
"Baskerville-Italic",
"Baskerville-SemiBold",
"Baskerville-SemiBoldItalic",
"BodoniSvtyTwoITCTT-Bold",
"BodoniSvtyTwoITCTT-Book",
"BodoniSvtyTwoITCTT-BookIta",
"BodoniSvtyTwoOSITCTT-Bold",
"BodoniSvtyTwoOSITCTT-Book",
"BodoniSvtyTwoOSITCTT-BookIt",
"BodoniSvtyTwoSCITCTT-Book",
"BodoniOrnamentsITCTT",
"BradleyHandITCTT-Bold",
"ChalkboardSE-Bold",
"ChalkboardSE-Light",
"ChalkboardSE-Regular",
"Chalkduster",
"Cochin",
"Cochin-Bold",
"Cochin-BoldItalic",
"Cochin-Italic",
"Copperplate",
"Copperplate-Bold",
"Copperplate-Light",
"Courier",
"Courier-Bold",
"Courier-BoldOblique",
"Courier-Oblique",
"CourierNewPS-BoldItalicMT",
"CourierNewPS-BoldMT",
"CourierNewPS-ItalicMT",
"CourierNewPSMT",
"Damascus",
"DamascusBold",
"DamascusMedium",
"DamascusSemiBold",
"DevanagariSangamMN",
"DevanagariSangamMN-Bold",
"Didot",
"Didot-Bold",
"Didot-Italic",
"DINAlternate-Bold",
"DINCondensed-Bold",
"EuphemiaUCAS",
"EuphemiaUCAS-Bold",
"EuphemiaUCAS-Italic",
"Farah",
"Futura-CondensedExtraBold",
"Futura-CondensedMedium",
"Futura-Medium",
"Futura-MediumItalic",
"GeezaPro",
"GeezaPro-Bold",
"GeezaPro-Light",
"Georgia",
"Georgia-Bold",
"Georgia-BoldItalic",
"Georgia-Italic",
"GillSans",
"GillSans-Bold",
"GillSans-BoldItalic",
"GillSans-Italic",
"GillSans-Light",
"GillSans-LightItalic",
"GujaratiSangamMN",
"GujaratiSangamMN-Bold",
"GurmukhiMN",
"GurmukhiMN-Bold",
"STHeitiSC-Light",
"STHeitiSC-Medium",
"STHeitiTC-Light",
"STHeitiTC-Medium",
"Helvetica",
"Helvetica-Bold",
"Helvetica-BoldOblique",
"Helvetica-Light",
"Helvetica-LightOblique",
"Helvetica-Oblique",
"HelveticaNeue",
"HelveticaNeue-Bold",
"HelveticaNeue-BoldItalic",
"HelveticaNeue-CondensedBlack",
"HelveticaNeue-CondensedBold",
"HelveticaNeue-Italic",
"HelveticaNeue-Light",
"HelveticaNeue-LightItalic",
"HelveticaNeue-Medium",
"HelveticaNeue-MediumItalic",
"HelveticaNeue-Thin",
"HelveticaNeue-Thin_Italic",
"HelveticaNeue-UltraLight",
"HelveticaNeue-UltraLightItalic",
"HiraKakuProN-W3",
"HiraKakuProN-W6",
"HiraMinProN-W3",
"HiraMinProN-W6",
"HoeflerText-Black",
"HoeflerText-BlackItalic",
"HoeflerText-Italic",
"HoeflerText-Regular",
"IowanOldStyle-Bold",
"IowanOldStyle-BoldItalic",
"IowanOldStyle-Italic",
"IowanOldStyle-Roman",
"Kailasa",
"Kailasa-Bold",
"KannadaSangamMN",
"KannadaSangamMN-Bold",
"MalayalamSangamMN",
"MalayalamSangamMN-Bold",
"Marion",
"Marion-Bold",
"Marion-Italic",
"Marion-Regular",
"MarkerFelt-Thin",
"MarkerFelt-Wide",
"Menlo-Bold",
"Menlo-BoldItalic",
"Menlo-Italic",
"Menlo-Regular",
"DiwanMishafi",
"Noteworthy-Bold",
"Noteworthy-Light",
"Optima-Bold",
"Optima-BoldItalic",
"Optima-ExtraBlack",
"Optima-Italic",
"Optima-Regular",
"OriyaSangamMN",
"OriyaSangamMN-Bold",
"Palatino-Bold",
"Palatino-BoldItalic",
"Palatino-Italic",
"Palatino-Roman",
"Papyrus",
"Papyrus-Condensed",
"PartyLetPlain",
"SavoyeLetPlain",
"SinhalaSangamMN",
"SinhalaSangamMN-Bold",
"SnellRoundhand",
"SnellRoundhand-Black",
"SnellRoundhand-Bold",
"Superclarendon-Black",
"Superclarendon-BlackItalic",
"Superclarendon-Bold",
"Superclarendon-BoldItalic",
"Superclarendon-Italic",
"Superclarendon-Light",
"Superclarendon-LightItalic",
"Superclarendon-Regular",
"Symbol",
"TamilSangamMN",
"TamilSangamMN-Bold",
"TeluguSangamMN",
"TeluguSangamMN-Bold",
/*"Thonburi",*/ // I see no difference from Thornburi-Light
"Thonburi-Bold",
"Thonburi-Light",
"TimesNewRomanPS-BoldItalicMT",
"TimesNewRomanPS-BoldMT",
"TimesNewRomanPS-ItalicMT",
"TimesNewRomanPSMT",
"Trebuchet-BoldItalic",
"TrebuchetMS",
"TrebuchetMS-Bold",
"TrebuchetMS-Italic",
"Verdana",
"Verdana-Bold",
"Verdana-BoldItalic",
"Verdana-Italic",
"Zapfino"];



/*
 * add new fonts here,then merge using merge() function in common.js
 * to create a new array for allFonts
 */
var newFonts = [
"Adelle",
"Abadi MT Condensed Extra Bold",
"Abadi MT Condensed Light",
"Academy Engraved LET",
"Adelle Basic",
"Adler",
"Adobe Arabic",
"Adobe Caslon Pro",
"Adobe Fan Heiti Std",
"Adobe Fangsong Std",
"Adobe Garamond Pro"
];




var allFonts = [
"1942 Report",
"28 Days Later",
"Aardvark",
"AGaramond RegularSC",
"AMS",
"AMS Mathematical Symbol",
"Abadi MT Condensed Extra Bold",
"Abadi MT Condensed Light",
"Academy Engraved LET",
"Adelle",
"Adelle Basic",
"Adler",
"Adobe Arabic",
"Adobe Caslon Pro",
"Adobe Caslon Pro Bold",
"Adobe Fan Heiti Std",
"Adobe Fangsong Std",
"Adobe Fangsong Std R",
"Adobe Garamond Pro",
"Adobe Garamond Pro Bold",
"Adobe Gothic Std",
"Adobe Hebrew",
"Adobe Heiti Std",
"Adobe Heiti Std R",
"Adobe Kaiti Std",
"Adobe Kaiti Std R",
"Adobe Ming Std",
"Adobe Ming Std L",
"Adobe Myungjo Std",
"Adobe Myungjo Std M",
"Adobe Pi Std",
"Adobe Sans MM",
"Adobe Serif MM",
"Adobe Song Std",
"Adobe Song Std L",
"Adobe 仿宋 Std",
"Adobe 仿宋 Std R",
"Adobe 宋体 Std",
"Adobe 宋体 Std L",
"Adobe 明體 Std",
"Adobe 明體 Std L",
"Adobe 楷体 Std",
"Adobe 楷体 Std R",
"Adobe 黑体 Std",
"Adobe 黑体 Std R",
"Adobe 명조 Std",
"Adobe 명조 Std M",
"Adonis",
"Advokat",
"Aegina",
"Aeroflot",
"AeroflotOpen",
"Aerospace",
"Agency FB",
"AgencyFB",
"Agenda",
"Aharoni",
"AidaBold",
"AidaBook",
"Airline",
"Airport",
"Airstream",
"AkronBoldCondensed",
"Aktuelle",
"Al Bayan",
"Alarich",
"Alaska",
"Alba",
"Alba Matter",
"Alba Super",
"Albany",
"Alberta",
"Albertus MT",
"Albertus MT Light",
"Alcatraz",
"Alexandria",
"Algarve",
"Algerian",
"AliceLight",
"AllegroOpen",
"Allgemeine",
"Alphabet",
"AlphabetOpen",
"AltonaBold",
"Amarillo",
"Amasis MT",
"American Typewriter",
"Amerika",
"Amienne",
"Amienne Ligatures",
"Analog",
"Anatevka",
"Anatol MN",
"Anchorage",
"Andale Mono",
"Andalus",
"Andrea",
"Anette",
"Angsana New",
"AngsanaUPC",
"Anime Ace",
"Annodomini",
"Antalya",
"Antares",
"AntaresOpen",
"Antigua",
"AntiqueOliTLig",
"AoyagiKouzanFontSousyo2",
"AoyagiKouzanFontT",
"AoyagiSosekiFont2",
"Apache",
"Apanage",
"ApanageBold",
"Aparajita",
"Aphrodite",
"Apple Braille",
"Apple Casual",
"Apple Chancery",
"Apple Color Emoji",
"Apple LiGothic",
"Apple LiSung",
"Apple SD Gothic Neo",
"Apple Symbols",
"AppleGothic",
"AppleMyungjo",
"Aquafont",
"Aquavit",
"Arabella",
"Arabic Typesetting",
"Arabien",
"Arcade",
"Archer",
"Archibald",
"Architekt",
"Arial",
"Arial Black",
"Arial Hebrew",
"Arial MT",
"Arial MT Std",
"Arial Narrow",
"Arial Narrow MT Std",
"Arial Rounded MT Bold",
"Arial Unicode MS",
"Arizona",
"Arlington",
"Armand",
"ArmandItalic",
"ArmedLemon",
"Arno Pro",
"Arno Pro Caption",
"Arno Pro Display",
"Arno Pro Light Display",
"Arno Pro SmText",
"Arno Pro Smbd",
"Arno Pro Smbd Caption",
"Arno Pro Smbd Display",
"Arno Pro Smbd SmText",
"Arno Pro Smbd Subhead",
"Arno Pro Subhead",
"Arphic Kuro-Maru-POP Heavy JIS",
"Arphic PKuro-Maru-POP Heavy JIS",
"Arphic PReisho Medium JIS2004",
"Arphic Reisho Medium JIS2004",
"ArtWorld MN",
"Artdeco MN",
"Artois",
"Asana Math",
"Ashley",
"Assistent",
"Aster MN",
"Asterisp Alpha",
"Asterisp Beta",
"Asterisp Delta",
"Asterisp Eta",
"Asterisp Gamma",
"Asterisp Iota",
"Asterisp Theta",
"Asterisp Zeta",
"Astigma",
"Athelas",
"Attention",
"Aubergine",
"Aurora",
"Auvergne",
"AuxinDemiBold",
"AuxinMedium",
"AvantGarde",
"Avantage",
"Avenir",
"Avenir LT 35 Light",
"Avenir LT 45 Book",
"Avenir LT 55 Roman",
"Avenir LT 65 Medium",
"Avenir Next",
"Avenir Next Condensed",
"Avignon",
"Ayuthaya",
"Azuki_font",
"Babylon",
"Baghdad",
"Baikal",
"Bajazzo",
"Bakery",
"Balduin",
"Ballade",
"Balloon",
"Balloon MN",
"BalloonOpen",
"BalloonShadow",
"Ballpark",
"Balmoral LT",
"Baltimore",
"Bambino",
"Banda Regular",
"Bandoneon",
"Bangla MN",
"Bangla Sangam MN",
"Bank Gothic",
"Baoli SC",
"Bariton",
"Barneybear",
"Baronesse",
"BaronesseBold",
"Barracuda",
"Barrage",
"Barrel",
"Barsoi",
"Basilika",
"BasilikaOpen",
"BasilikaShadow",
"Baskerville",
"Baskerville MT",
"Baskerville Old Face",
"Batang",
"BatangChe",
"Bauhaus 93",
"Bawdy",
"BeLucianBook",
"BeLucianBookItalic",
"BeLucianDemi",
"BeLucianUltra",
"Beatrice",
"Beetlejuice",
"Bell Gothic Std",
"Bell Gothic Std Black",
"Bell Gothic Std Light",
"Bell MT",
"BellamyBold",
"BellamyExtraBold",
"Bellevue",
"Bello",
"Bello Pro",
"Benediktin",
"Bengasi",
"BengasiBold",
"BenjaminGothicMedium",
"BenjaminGothicWide",
"Berenice",
"Bergamo",
"Berlin",
"Berlin Sans FB",
"Berlin Sans FB Demi",
"Bermuda",
"Bernard MT Condensed",
"Berthold Akzidenz Grotesk BE",
"Beyond Wonderland",
"Biathlon",
"BiauKai",
"Bickham Script MM",
"Bickham Script MM Orn",
"Bickham Script One",
"Bickham Script Pro",
"Bickham Script Pro Regular",
"Bickham Script Pro Semibold",
"Bickham Script Three",
"BickhamScriptFancy2",
"Bienvenue",
"Biffo MT",
"Big Caslon",
"Bigbrother",
"Bilder",
"Billard",
"Billboard",
"Billett",
"Billings",
"Binny Old Style MT",
"Birch Std",
"Birdie",
"Bitstream Charter",
"Bitstream Cyberbit",
"Bitstream Vera Sans",
"Bitstream Vera Sans Mono",
"Bitstream Vera Serif",
"Bizarr",
"Blackadder ITC",
"Blackmoor LET",
"Blackoak Std",
"Blackout",
"Blado MT",
"Blaetter",
"BlairMdITC TT",
"Blue Highway",
"Blue Highway Condensed",
"Blue Highway D Type",
"Blue Highway Linocut",
"Boardwalk",
"BodegaSans",
"BodegaSans-BlackSmallcaps",
"BodegaSans-Light",
"BodegaSans-Medium",
"BodegaSans-MediumOldstyle",
"BodegaSans-MediumSmallcaps",
"BodegaSerif",
"Bodoni",
"Bodoni MT",
"Bodoni MT Black",
"Bodoni MT Condensed",
"Bodoni MT Poster Compressed",
"Bodoni Ornaments ITC TT",
"Bodoni SvtyTwo ITC TT",
"Bodoni SvtyTwo OS ITC TT",
"Bodoni SvtyTwo SC ITC TT",
"Bomr",
"Bonanza",
"Book Antiqua",
"BookAntiqua",
"Bookman Old Style",
"Bookshelf Symbol 7",
"BookshelfSymbol1",
"Boopee",
"Bordeaux Roman Bold LET",
"Boton",
"Bouquet",
"Bowling",
"Bradley Hand ITC",
"Bradley Hand ITC TT",
"Braggadocio",
"Braggadocio MT",
"Brasilia",
"Bravour",
"Bretagne",
"Brillant",
"BrillantOpen",
"Brio MN",
"Brisbane",
"Britannic Bold",
"Broadway",
"Broken",
"Browallia New",
"BrowalliaUPC",
"Brunhild",
"Brush Script MT",
"Brush Script Std",
"Bruxelles",
"Buchkunst",
"BuchkunstBold",
"Buenosaires",
"Bulldozer",
"Bulletin Typewriter MN",
"Bumblebee",
"BumblebeeItalic",
"BumblebeeOpen",
"BureauAgency",
"BureauAgencyBold",
"BureauEagleBold",
"BureauEmpire",
"BureauEmpireItalic",
"BureauGrotesque",
"BurlingtonShadow",
"Buster",
"Butcher",
"Butterfly",
"Caesar",
"Cafeteria",
"Caflisch Script Pro",
"Cagliari",
"Calibri",
"Californian FB",
"Caligra MN",
"Caligula",
"Calisto MT",
"Calvados",
"Calypso",
"Cambria",
"Cambria Math",
"Camilla",
"CamillaOpen",
"Camion",
"CamionBold",
"Campus MN",
"Candara",
"Candida",
"Canopus",
"CanopusOpen",
"Capitals",
"Capitol",
"Capolar",
"Caravelle",
"CarbonBlock",
"CarbonType",
"CardCamio MN",
"CarlosNoeight",
"CarlosNoseven",
"Carnivale",
"Carnivalee Freakshow",
"Carnivalee Freakshow Demo",
"Carplate MN",
"Carrera",
"Carrousel",
"Carton",
"Cartoon",
"CartoonDemiBold",
"Carwash",
"Casino",
"Cassius",
"Castellar",
"Casting",
"Castle",
"Casual",
"Cataaca",
"Catania",
"Catweazle",
"Cecilia",
"Celtic Garamond the 2nd",
"Celtic MN",
"Centaur",
"Centaur Expert MT",
"Centaur MT",
"Centime",
"Centralpark",
"Centurio",
"Century",
"Century Gothic",
"Century Schoolbook",
"Century Schoolbook L",
"Cessna",
"Chalkboard",
"Chalkboard SE",
"Chalkduster",
"Challenger",
"ChallengerOpen",
"ChampagneBold",
"ChampagneItalic",
"ChampagneNormal",
"Champignon",
"Champignon Alt Swash",
"Chancery",
"Chaparral Pro",
"Chapel",
"Charcoal CY",
"Charlemagne Std",
"Charlotte",
"Charmeur",
"Charter",
"Checkpoint",
"Chelsea",
"Cherbourg",
"Cheri",
"Cheri Liney",
"Chestnut",
"Cheyenne",
"Chihuahua",
"Chiller",
"Chinese",
"Choc MN",
"Chocolate",
"Chrismasstars",
"Chronik",
"Cinderella",
"Circus",
"Circus MN",
"Clarendon",
"Classic",
"Classic Script MN",
"Clean",
"ClearlyU",
"ClearlyU Alternate Glyphs",
"ClearlyU PUA",
"Cleopatra",
"Cleveland",
"Client",
"Cloister Black",
"Cochin",
"Cochise",
"Cockpit",
"CockpitOpen",
"Code2000",
"Code2001",
"Code2002",
"College",
"ColoniaBrush",
"Colonna MT",
"ColonnaMT",
"Colorado",
"Columbus",
"Columbus Exp MT",
"Columbus MT",
"Comic Sans MS",
"Comic Strip MN",
"Comix Heavy",
"Commander",
"Commercial Script",
"Commercial Script MN",
"Commonwealth",
"Compacta",
"Computer Modern",
"Concorde",
"Consolas",
"Constantia",
"Contest MN",
"Cooper Black",
"Cooper Std",
"Cooper Std Black",
"Copacabana",
"Copperplate",
"Copperplate Gothic Bold",
"Copperplate Gothic Light",
"Corbel",
"Cordia New",
"CordiaUPC",
"Cordoba",
"Cornish",
"Corona",
"Corsiva Hebrew",
"Cosenza",
"CosenzaBold",
"CosenzaItalic",
"Countdown",
"CountdownOpen",
"Courier",
"Courier 10 Pitch",
"Courier New",
"Courier Std",
"Cracked",
"CrawfordOldStyle",
"Creampuff",
"Creativ",
"Cremona",
"CremonaOpen",
"Crocodile",
"Culture",
"Cumberland",
"Cupido",
"Curacao",
"Curlz MT",
"Cursor",
"CutterItalic",
"CutterRoman",
"CyprusBold",
"CyprusLight",
"CyprusMedium",
"DFBrushRD-W12",
"DFBrushSQ-W12",
"DFCraftYu-W7",
"DFFuun-W12",
"DFGBrushRD-W12",
"DFGBrushSQ-W12",
"DFGCraftYu-W7",
"DFGFuun-W12",
"DFGGothic-UB",
"DFGKaiSho-SU",
"DFGKoIn-W4",
"DFGLeiGaSo-W9",
"DFGMaruGothic-SU",
"DFGMaruGothic-UB",
"DFGMincho-UB",
"DFGPOPCorn-W12",
"DFGRuLei-W5",
"DFGothic-EB",
"DFGothic-UB",
"DFKai-SB",
"DFKaiSho-SU",
"DFKoIn-W4",
"DFLeiGaSo-W9",
"DFMaruGothic-SU",
"DFMaruGothic-UB",
"DFMaruMoji-W3",
"DFMincho-UB",
"DFPBrushRD-W12",
"DFPBrushSQ-W12",
"DFPCraftYu-W7",
"DFPFuun-W12",
"DFPGothic-EB",
"DFPGothic-UB",
"DFPKaiSho-SU",
"DFPLeiGaSo-W9",
"DFPMaruGothic-SU",
"DFPMaruGothic-UB",
"DFPMaruMoji-W3",
"DFPMincho-UB",
"DFPOP-SB",
"DFPOPCorn-W12",
"DFPPOP-SB",
"DFPPOPCorn-W12",
"DFRuLei-W5",
"DFSoKing-W3",
"DIN Alternate",
"DIN Condensed",
"DIN-Bold",
"DIN-BoldAlternate",
"DIN-BoldExpert",
"DINSchrift",
"Daemon",
"DaemonBold",
"Dagobert",
"Dakota",
"Dalton",
"DanielScript",
"Dante Expert MT",
"Danton",
"Daphne",
"Darling",
"Dartmoor",
"DaunPenh",
"Davenport",
"David",
"Davofont",
"Days One",
"DecoType Naskh",
"DejaVu Sans",
"DejaVu Sans Condensed",
"DejaVu Sans Light",
"DejaVu Sans Mono",
"DejaVu Serif",
"DejaVu Serif Condensed",
"Deming EP",
"Desdemona",
"Desperado",
"Despot",
"Devanagari MT",
"Devanagari Sangam MN",
"Deventer",
"Devise",
"Dewsbury",
"Diabolo",
"Dickeberta",
"Didot",
"Diego",
"DilleniaUPC",
"Dimension",
"Dingbats",
"Dingsda",
"Diplomat",
"Dirigent",
"Dirt2 SoulStalker",
"DirtyBakersDozen",
"Divingboard",
"Doctor",
"DoctorBold",
"DokChampa",
"Dollar",
"DollarItalic",
"Dolomit",
"Domaene",
"Dominikus",
"Domino",
"Donald",
"DonaldOpen",
"Doolittle",
"Dorothee",
"Dotum",
"DotumChe",
"Downtown",
"Drachenfels",
"Droid",
"Droid Sans",
"Droid Sans Arabic",
"Droid Sans Fallback",
"Droid Sans Hebrew",
"Droid Sans Japanese",
"Droid Sans Mono",
"Droid Sans Thai",
"Droid Serif",
"Dschidda",
"Dubarry",
"Dubbeldik MN",
"Dynamo MN",
"EPSON 丸ゴシック体Ｍ",
"EPSON 太丸ゴシック体Ｂ",
"EPSON 太明朝体Ｂ",
"EPSON 太行書体Ｂ",
"EPSON 太角ゴシック体Ｂ",
"EPSON 教科書体Ｍ",
"EPSON 正楷書体Ｍ",
"EPSON 行書体Ｍ",
"Eagle",
"East Syriac Adiabene",
"East Syriac Ctesiphon",
"Eastgothic",
"Ebrima",
"Eccentric Std",
"Edmondsans",
"Edwardian Script ITC",
"Elbrus",
"Elefont",
"Elena",
"Elephant",
"Eleven",
"Ellington MT",
"ElliotOne",
"ElliotTwo",
"Emilia",
"EmiliaBold",
"Engravers MT",
"Ensemble",
"Entebbe",
"Enterprise",
"Enzyklika",
"Ephesus",
"Epigone",
"Epiphon",
"Episode",
"Equipe",
"EquipeMedium",
"Eras Bold ITC",
"Eras Demi ITC",
"Eras Light ITC",
"Eras Medium ITC",
"Eremitage",
"ErieLight",
"Escapade",
"Esperanto",
"Esther",
"Estrangelo Antioch",
"Estrangelo Edessa",
"Estrangelo Midyat",
"Estrangelo Nisibin",
"Estrangelo Nisibin Outline",
"Estrangelo Quenneshrin",
"Estrangelo Talada",
"Estrangelo TurAbdin",
"Estro MN",
"Etappe",
"Etikette",
"Euboea",
"EucrosiaUPC",
"Eugene",
"Euler",
"Euphemia",
"Euphemia UCAS",
"Euratom",
"Eureka",
"Eurostile",
"Eurostile Extended",
"Eurostile LT",
"Eurostile LT Bold",
"Eurostile LT Condensed",
"Eurostile LT ExtendedTwo",
"Euterpe",
"Exponat",
"Expose",
"Extreme",
"FFF Tusj",
"FGTCOMGM",
"FGTCOMKM",
"Facette",
"Fairbanks",
"Fairytale",
"Falkland",
"Falstaff",
"Fanfare",
"FangSong",
"Faustus",
"FaustusBold",
"Favorit",
"Fayette",
"Feijoa",
"Felicitas",
"Felix Titling",
"Feuilleton",
"Fidelio",
"Fidelio MN",
"Fifties Heavy",
"Fifties Hollow",
"Figa",
"Figaro",
"FineTextLight",
"Finesse",
"Firestone",
"Fixed",
"Fixedsys",
"Flamenco",
"Flipper",
"Flower",
"FontOne",
"Fontainebleau",
"Fontane",
"Footlight MT Light",
"Forte",
"Forte MT",
"Four Winds V2",
"Foxtrott",
"FrancoisBold",
"FrancoisBoldItalic",
"FrancoisLight",
"FrancoisLightItalic",
"FrancoisMedium",
"FrancoisMediumItalic",
"FrancoisRegular",
"FrancoisRegularItalic",
"FrankRuehl",
"Franklin Gothic Book",
"Franklin Gothic Demi",
"Franklin Gothic Demi Cond",
"Franklin Gothic Heavy",
"Franklin Gothic Medium",
"Franklin Gothic Medium Cond",
"FreeEuro",
"FreeMono",
"FreeSans",
"FreeSerif",
"FreebooterScript",
"FreesiaUPC",
"Freestyle Script",
"Freezer",
"FreightSans Pro",
"French Script MT",
"FrenchcarDemiBold",
"Friedrich",
"Frutiger",
"Frutiger CE 45 Light",
"Frutiger CE 55 Roman",
"Frutiger CE 95 Ultra Black",
"Frutiger LT 45 Light",
"Frutiger LT 47 LightCn",
"Frutiger LT 55 Roman",
"Frutiger LT 57 Cn",
"Frutiger LT 87 ExtraBlackCn",
"Frutiger LT 95 UltraBlack",
"Fumarea",
"Fumo Dropshadow MN",
"Funboy",
"Funhouse",
"Furore",
"Futura",
"Futura LT Book",
"Futura LT Condensed",
"Futura LT CondensedExtraBold",
"Futura LT CondensedLight",
"Futura LT ExtraBold",
"Futura LT Light",
"Futura LT Medium",
"GT2000-01",
"GaberBold",
"Gabriola",
"Galago",
"Galaxie Cassiopeia",
"Galaxie Cassiopeia Basic",
"Galaxie Polaris",
"Galba MN",
"Galeere",
"Gallery",
"Gangway",
"Garamond",
"Garamond Premier Pro",
"Garamond Premr Pro",
"Garamond Premr Pro Smbd",
"Garfield",
"Gasparone",
"Gautami",
"Geeza Pro",
"Gemini",
"GeminiOpen",
"Genesis",
"Geneva",
"Geneva CY",
"Genius",
"GeniusItalic",
"Genoveva",
"GenovevaItalic",
"Gentium Basic",
"Gentium Book Basic",
"Geoffrey",
"Georgia",
"Gerona",
"Geronimo",
"Getaway",
"Gianna",
"Giddyup Std",
"Gigi",
"Gill Sans",
"Gill Sans BoldExtraCondensed",
"Gill Sans ExtraBoldDisplay",
"Gill Sans LightShadowed",
"Gill Sans MT",
"Gill Sans MT Condensed",
"Gill Sans MT Ext Condensed Bold",
"Gill Sans MT Extra Bold",
"Gill Sans MT Light",
"Gill Sans MT Ultra Bold",
"Gill Sans MT Ultra Bold Cond",
"Gill Sans Shadowed",
"Gill Sans Ultra Bold",
"Gill Sans Ultra Bold Condensed",
"Giovanni",
"GiovanniItalic",
"GiovanniOpen",
"Gisha",
"Gitarre",
"Giza",
"Glamour",
"Global",
"GlobeGothic MN",
"Globus",
"Gloucester MT Extra Condensed",
"Glowworm MN",
"Goha-Tibeb Zemen",
"Gomorrah",
"Gondorf",
"Gothics",
"Gothique MN",
"Gotthard",
"Goudy Old Style",
"Goudy Stout",
"Gourmet",
"Graffiato",
"Graphics",
"Graphik",
"Graveur",
"Green piloww",
"Gremlin",
"Griseldis",
"Grisette",
"Grotesque MT",
"Gujarati MT",
"Gujarati Sangam MN",
"Gulim",
"GulimChe",
"Gulliver",
"GungSeo",
"Gungsuh",
"GungsuhChe",
"Gurmukhi MN",
"Gurmukhi MT",
"Gurmukhi Sangam MN",
"Gustav",
"HAN NOM A",
"HAN NOM B",
"HGGothicE",
"HGGothicEPRO",
"HGGothicM",
"HGGyoshotai",
"HGHigemoji",
"HGKasaneKakugothicH",
"HGKyokashotai",
"HGMaruGothicMPRO",
"HGMinchoB",
"HGMinchoE",
"HGPGothicE",
"HGPGothicM",
"HGPGyoshotai",
"HGPHigemoji",
"HGPKasaneKakugothicH",
"HGPKyokashotai",
"HGPMinchoB",
"HGPMinchoE",
"HGPSoeiKakugothicUB",
"HGPSoeiKakupoptai",
"HGPSoeiPresenceEB",
"HGPrettyFrankH",
"HGP創英角ｺﾞｼｯｸUB",
"HGP創英角ﾎﾟｯﾌﾟ体",
"HGP創英ﾌﾟﾚｾﾞﾝｽEB",
"HGP教科書体",
"HGP明朝B",
"HGP明朝E",
"HGP行書体",
"HGPｺﾞｼｯｸE",
"HGPｺﾞｼｯｸM",
"HGSGothicE",
"HGSGothicM",
"HGSGyoshotai",
"HGSHigemoji",
"HGSKasaneKakugothicH",
"HGSKyokashotai",
"HGSMinchoB",
"HGSMinchoE",
"HGSSoeiKakugothicUB",
"HGSSoeiKakupoptai",
"HGSSoeiPresenceEB",
"HGSeikaishotaiPRO",
"HGSoeiKakugothicUB",
"HGSoeiKakupoptai",
"HGSoeiPresenceEB",
"HVD Comic Serif Pro",
"Habitus",
"Haettenschweiler",
"HakusyuGokubutoKaisyoKyo",
"HakusyuGyosyoKyokan",
"HakusyuInsoutaiKyo",
"HakusyuKaisyoKyokan",
"HakusyuKointaiKyokan",
"HakusyuReisyoKyokan",
"HakusyuSeigyosyoKyo",
"HakusyuSousyoKyo",
"HakusyuTenkoinKyo",
"HakusyuTensyoKyokan",
"Halifax",
"Hallodolly",
"Hamilton",
"Hamlet",
"Hammond",
"HanaMin",
"HandFont",
"Handage AOE",
"Handicap",
"Handmade",
"Handwriting - Dakota",
"Hannotate SC",
"Hannotate TC",
"Hanseat",
"Hansson Stencil MN",
"HanziPen SC",
"HanziPen TC",
"HappyBirthday",
"Harddisc",
"Harlow Solid Italic",
"Harpune",
"Harrington",
"Hattrick",
"HattrickOpen",
"HattrickShadow",
"HeadLineA",
"Headline MT",
"Hei",
"Heiti SC",
"Heiti TC",
"Heiti-간체",
"Heiti-번체",
"HelenaDemiBold",
"HelenaScript",
"Helvetica",
"Helvetica CE 35 Thin",
"Helvetica CE 55 Roman",
"Helvetica CY",
"Helvetica Neue",
"Helvetica Neue LT Com",
"Helvetica Neue LT Pro",
"Helvetica Neue LT Std",
"Helvetica Rounded",
"Helvetica-Black",
"HelveticaCondensed",
"HelveticaNeue-CondensedBold",
"HelveticaNeue-Ex",
"HelveticaNeue-Cn",
"HelveticaNeue-BdOutline",
"HelveticaNeue-BlackEx",
"HelveticaNeue-Black",
"HelveticaNeue-BlackCn",
"HelveticaNeue-Bold",
"HelveticaNeue-BoldItalic",
"HelveticaNeue-LightEx",
"HelveticaNeue-Light",
"HelveticaNeue-LightCn",
"HelveticaNeue-MdEx",
"HelveticaNeue-Medium",
"HelveticaNeue-MdCn",
"HelveticaNeue-Roman",
"HelveticaNeue-ThinEx",
"HelveticaNeue-Thin",
"HelveticaNeue-ThinCn",
"HelveticaNeue-UltLtEx",
"HelveticaNeue-UltLight",
"HelveticaNeue-UltLtCn",
"HelveticaNeue-XBlkCn",
"HelveticaNeueLT Com 65 Md",
"Herculanum",
"Hetaji",
"Hibiscus",
"High Tower Text",
"HighNoon",
"Hillary",
"Hillbilly",
"Hillman",
"Himalaya",
"Hiragino Kaku Gothic Pro",
"Hiragino Kaku Gothic Pro W3",
"Hiragino Kaku Gothic Pro W6",
"Hiragino Kaku Gothic ProN",
"Hiragino Kaku Gothic ProN W3",
"Hiragino Kaku Gothic ProN W6",
"Hiragino Kaku Gothic Std",
"Hiragino Kaku Gothic Std W8",
"Hiragino Kaku Gothic StdN",
"Hiragino Kaku Gothic StdN W8",
"Hiragino Maru Gothic Pro",
"Hiragino Maru Gothic Pro W4",
"Hiragino Maru Gothic ProN",
"Hiragino Maru Gothic ProN W4",
"Hiragino Mincho Pro",
"Hiragino Mincho Pro W3",
"Hiragino Mincho Pro W6",
"Hiragino Mincho ProN",
"Hiragino Mincho ProN W3",
"Hiragino Mincho ProN W6",
"Hiragino Sans GB",
"Hiragino Sans GB W3",
"Hiragino Sans GB W6",
"Hiruko",
"Hobo Std",
"Hoefler Text",
"Hohenfels",
"Hohenstaufen",
"Holiday-MDJP02",
"Hollywood",
"Hombre",
"Hongkong",
"Honorius",
"HorizonWide",
"Horror",
"Hotel MN",
"Hotzenplotz",
"Houston",
"Howard",
"HuiFont",
"Hurricane",
"Hyazinth",
"ITC Avant Garde Gothic",
"ITC Eras",
"ITC Officina Sans",
"ITCFranklinGothic LT Book",
"ITCFranklinGothic LT BookCn",
"ITCFranklinGothic LT BookCp",
"ITCFranklinGothic LT BookXCp",
"ITCFranklinGothic LT Med",
"ITCFranklinGothic LT MedCn",
"Icecream",
"Idomeneo",
"IdomeneoOpen",
"Iguanodon",
"Impact",
"Impact Label",
"Impact Label Reversed",
"Impasto",
"Imperia",
"Imprint MT Shadow",
"InaiMathi",
"Inconsolata",
"Indigo Joker",
"Infant",
"Inferno",
"InfinityCBold",
"InfinityCMedium",
"InfinitySTBoldItalic",
"InfinitySTMedium",
"InfinityTExtraBold",
"Inflex MT",
"Informal Roman",
"Intaglio",
"Intermezzo",
"Interstate",
"Iowan Old Style",
"Iraklion",
"IrisUPC",
"Ironmonger",
"Isfahan",
"Iskoola Pota",
"Isolde",
"Isophan",
"Italian Old Style MT",
"Ithaka",
"Jackson MN",
"Jailhouse",
"JaneAusten",
"January",
"JanuaryOpen",
"Jasmin",
"JasminBold",
"JasmineUPC",
"Jazz",
"Jazz LET",
"JazzCord",
"JazzPerc",
"JazzText",
"JazzTextExtended",
"Jeepjeep",
"Jenufa",
"Jeremiah",
"JerseyMediumExpanded",
"Jiddish",
"Jillsville",
"Jobber",
"Johannes",
"Jokerman",
"Jonathan",
"JonathanBoldCondensed",
"JonathanBoldItalic",
"Jongleur",
"Journal",
"Judith",
"Juice ITC",
"Jukebox",
"JukeboxBold",
"JukeboxInline",
"Julia-HandScript",
"JuliusLight",
"JuliusRegular",
"Jungle",
"JungleItalic",
"Jura",
"Juventus",
"Kai",
"KaiTi",
"Kailasa",
"Kaiti SC",
"Kaiti TC",
"Kakukaku1",
"Kalahari",
"Kaleidoskop",
"Kalinga",
"Kamille",
"Kannada MN",
"Kannada Sangam MN",
"Kapriole",
"Karbon",
"Kardinal",
"Karthago",
"KarthagoInline",
"KarthagoOpen",
"KarthagoShadow",
"Kartika",
"Kasimir",
"Katmandu",
"Kaufmann",
"Kefa",
"Khmer Sangam MN",
"Khmer UI",
"Kidnapper",
"Kiloji",
"Kimberley",
"Kimono",
"Kindergarden",
"Kino MT",
"Kismet",
"Kisuaheli",
"Klang MT",
"Klavier",
"Kleptocracy",
"Klimbim",
"Kobold",
"KodchiangUPC",
"Koepenick",
"Kokila",
"Kokonor",
"Kolibri",
"Kolumbus",
"Komika Axis",
"Konfuzius",
"Konstanza",
"Konvoi",
"Kopernikus",
"KouzanBrushFont",
"KouzanBrushFontGyousyo",
"KouzanBrushFontSousyo",
"Kozuka Gothic Pr6N",
"Kozuka Gothic Pro",
"Kozuka Gothic Pro B",
"Kozuka Gothic Pro EL",
"Kozuka Gothic Pro H",
"Kozuka Gothic Pro L",
"Kozuka Gothic Pro M",
"Kozuka Gothic Pro R",
"Kozuka Mincho Pr6N",
"Kozuka Mincho Pro",
"Kozuka Mincho Pro B",
"Kozuka Mincho Pro EL",
"Kozuka Mincho Pro H",
"Kozuka Mincho Pro L",
"Kozuka Mincho Pro M",
"Kozuka Mincho Pro R",
"Krini",
"Krinitsky",
"Kristen ITC",
"Krungthep",
"KufiStandardGK",
"Kumulus",
"Kunibert",
"Kunstler Script",
"LMMathExtension10",
"LMMathItalic10",
"LMMathItalic12",
"LMMathItalic5",
"LMMathItalic6",
"LMMathItalic7",
"LMMathItalic8",
"LMMathItalic9",
"LMMathSymbols10",
"LMMathSymbols5",
"LMMathSymbols6",
"LMMathSymbols7",
"LMMathSymbols8",
"LMMathSymbols9",
"LMMono10",
"LMMono12",
"LMMono8",
"LMMono9",
"LMMonoCaps10",
"LMMonoLt10",
"LMMonoLtCond10",
"LMMonoProp10",
"LMMonoPropLt10",
"LMMonoSlant10",
"LMRoman10",
"LMRoman12",
"LMRoman17",
"LMRoman5",
"LMRoman6",
"LMRoman7",
"LMRoman8",
"LMRoman9",
"LMRomanCaps10",
"LMRomanDemi10",
"LMRomanDunh10",
"LMRomanSlant10",
"LMRomanSlant12",
"LMRomanSlant17",
"LMRomanSlant8",
"LMRomanSlant9",
"LMRomanUnsl10",
"LMSans10",
"LMSans12",
"LMSans17",
"LMSans8",
"LMSans9",
"LMSansDemiCond10",
"LMSansQuot8",
"LOGO10",
"LOGO8",
"LOGO9",
"LOGOBF10",
"LOGOD10",
"LOGOSL10",
"LOGOSL8",
"LOGOSL9",
"LSTKClarendon",
"LSTKClarendonBold",
"LSTKGaraPen",
"LaTeX",
"Labrador",
"Labyrinth",
"Lady Rene",
"LaguneBold",
"LaguneExtraBold",
"LaguneLight",
"Laibach",
"Lambada",
"LangerInitialien",
"Languste",
"Lansing",
"Lantinghei SC",
"Lantinghei TC",
"Lao MN",
"Lao Sangam MN",
"Lao UI",
"Larabiefont",
"Larissa",
"LarissaOpen",
"LastResort",
"Lateran",
"LateranItalic",
"LateranOpen",
"Latha",
"Latin Modern Mono",
"Latin Modern Mono Caps",
"Latin Modern Mono Light",
"Latin Modern Mono Light Cond",
"Latin Modern Mono Prop",
"Latin Modern Mono Prop Light",
"Latin Modern Mono Slanted",
"Latin Modern Roman",
"Latin Modern Roman Caps",
"Latin Modern Roman Demi",
"Latin Modern Roman Dunhill",
"Latin Modern Roman Slanted",
"Latin Modern Roman Unslanted",
"Latin Modern Sans",
"Latin Modern Sans Demi Cond",
"Latin Modern Sans Quotation",
"Latina MN",
"Lato",
"Laurin",
"LaurinText",
"Lausanne",
"LausanneItalic",
"Lavendel",
"Leelawadee",
"Leningrad",
"Leonardo",
"LeonhardBoldCondensed",
"Leopard MN",
"Letter Gothic MT",
"Letter Gothic Std",
"Levenim MT",
"Lewistown",
"LiHei Pro",
"LiSong Pro",
"Liberance",
"Liberation Sans Narrow",
"Libian SC",
"Libre Baskerville",
"Lifetime",
"Lightbrigade",
"Liliput",
"LiliputItalic",
"Lillehammer",
"LilyUPC",
"Limousine",
"LimousineOpen",
"Lincoln",
"Linford",
"Lionel",
"Lionheart",
"Lithos Pro",
"Lithos Pro Regular",
"LizardMedieval",
"Lohengrin",
"Lokomotive",
"London",
"Longview",
"Lorient",
"Louisiana",
"Louisville",
"Lucida",
"Lucida Blackletter",
"Lucida Bright",
"Lucida Calligraphy",
"Lucida Console",
"Lucida Fax",
"Lucida Grande",
"Lucida Handwriting",
"Lucida Sans",
"Lucida Sans Typewriter",
"Lucida Sans Unicode",
"LucidaBright",
"LucidaTypewriter",
"Luckyluke",
"Lugano",
"Lupine",
"Lutetia",
"Luxi Mono",
"Luxi Sans",
"Luxi Serif",
"Luzern",
"Lydiane",
"MGrotesque",
"MGrotesque-Black",
"MGrotesque-Bold",
"MGrotesque-Condensed",
"MGrotesque-ExtraCondensed",
"MGrotesque-Italic",
"MGrotesque-Light",
"MGrotesque-LightCondensed",
"MGrotesque-LightItalic",
"MPlantin",
"MPlantin-Bold",
"MPlantin-BoldCondensed",
"MPlantin-BoldItalic",
"MPlantin-Italic",
"MPlantin-Light",
"MPlantin-LightItalic",
"MPlantin-SemiBold",
"MPlantin-SemiBoldItalic",
"MRockwell",
"MRockwell-Bold",
"MRockwell-BoldCondensed",
"MRockwell-BoldItalic",
"MRockwell-Condensed",
"MRockwell-ExtraBold",
"MRockwell-Italic",
"MRockwell-Light",
"MRockwell-LightItalic",
"MS Gothic",
"MS Mincho",
"MS Outlook",
"MS PGothic",
"MS PMincho",
"MS Reference Sans Serif",
"MS Reference Specialty",
"MS Sans Serif",
"MS Serif",
"MS UI Gothic",
"MS-PRGothic",
"MT Extra",
"MV Boli",
"Machiavelli",
"Madeira",
"Madison",
"Maeggy",
"Magazin",
"Magneto",
"Mahagoni",
"Maiandra GD",
"Maiers Nr.21 Pro",
"MakibaFont",
"Malayalam MN",
"Malayalam Sangam MN",
"Malgun Gothic",
"Malmoe",
"Managua",
"Manege",
"Manfnt",
"Mangal",
"Manguste",
"MangusteOpen",
"Manhattan",
"Manuscript",
"Marcanton",
"Marcel",
"MarcelItalic",
"Marcelle Script",
"Marcelle Swashes",
"Marchese",
"Marengo",
"Marina",
"Marion",
"Marker Felt",
"Marlett",
"Marshall",
"Maryland",
"Matterhorn",
"Matura",
"Matura MT Script Capitals",
"Maxwell",
"Mecheria",
"Medley",
"Medusa",
"Meiryo",
"Meiryo UI",
"Melanie",
"Memento",
"Menlo",
"Mephisto",
"Mercator",
"MercatorCondensed",
"Mercurius Bold Script MT",
"Mesquite Std",
"Mestize",
"Meta-Bold",
"Meta-Caps",
"Meta-Normal",
"Metallica",
"Meteor",
"Meteorit",
"Mexico",
"Mezzoforte",
"Michael",
"Michelle",
"Michigan",
"Micro.pcf",
"Microsoft Himalaya",
"Microsoft JhengHei",
"Microsoft New Tai Lue",
"Microsoft PhagsPa",
"Microsoft Sans Serif",
"Microsoft Tai Le",
"Microsoft Uighur",
"Microsoft YaHei",
"Microsoft Yi Baiti",
"Midwest",
"Mikachan",
"Mikachan-P",
"Mikachan-PB",
"Mikachan-PS",
"Mikado",
"MikadoItalic",
"MilanBold",
"Milton MN",
"MingLiU",
"MingLiU-ExtB",
"MingLiU_HKSCS",
"MingLiU_HKSCS-ExtB",
"Minicar",
"Minion Pro",
"Minion Pro Cond",
"Minion Pro Med",
"Minion Pro SmBd",
"Minya",
"Minya Nouvelle",
"Mirage",
"MirageOpen",
"Mirakel",
"Miranda",
"Miriam",
"Miriam Fixed",
"Mirror",
"Misfits",
"Mission Script",
"Mistral",
"Modern No. 20",
"Mohair",
"Mona Lisa Solid ITC TT",
"Monaco",
"Monalisa",
"Monarch",
"Mongolian Baiti",
"Monoline Script MT",
"Monophon",
"MonophonOpen",
"MonophonShadow",
"Monopol",
"Monotype Corsiva",
"Monotype Sorts",
"Monsignore",
"Monster hunter",
"Montaigne",
"Monterey",
"MoolBoran",
"Moon font",
"Moon font-PRO",
"Moredings",
"Morelle",
"Mormone",
"Moulinrouge",
"Moviestar",
"Mshtakan",
"Mufferaw",
"Murmansk",
"Museo Slab",
"MusicalSymbols",
"Mustang",
"MyType!",
"Myanmar MN",
"Myanmar Sangam MN",
"Mykena",
"Myriad Pro",
"Myriad Pro Cond",
"Myriad Pro Light",
"Myriad Web Pro",
"Myriade",
"MyriadeOpen",
"Mythos",
"NSimSun",
"Nachtwache",
"Nadeem",
"Nanum Brush Script",
"Nanum Gothic",
"Nanum Myeongjo",
"Nanum Pen Script",
"Narbonne",
"NarbonneOpen",
"Narkisim",
"Nasalization",
"Natalie",
"National",
"Navajo",
"NavajoBlack",
"Nazareth",
"NazarethOpen",
"Nebraska",
"Nelson",
"Nemesis",
"NeoGeo_TR",
"Neographik MT",
"NHaasGroteskDSStd-75Bd",
"NeueHaasGrotesk",
"Neuropol Nova",
"Neuropol Nova Cnd",
"Neuropol Nova Cnd Lite",
"Neuropol Nova Lite",
"Neuropol Nova Xp",
"Neuropol Nova Xp Lt",
"Neuropol X",
"Neuropol X Burn",
"Neuropol X Cnd",
"Neuropol X Cnd Lite",
"Neuropol X Lite",
"Neuropol X Xp",
"Neuropol X Xp Lite",
"Neutraface",
"New Century Schoolbook",
"New Clarendon",
"New Peninim MT",
"Newclips",
"News Cycle",
"News Gothic",
"News Gothic MT",
"NewsGotTLig",
"Newspaper",
"Niagara",
"Niagara Engraved",
"Niagara Solid",
"Nicesymbols",
"Night Sky_TR",
"Nijmwegen",
"Nimbus Mono L",
"Nimbus Roman No9 L",
"Nimbus Sans L",
"Nimrod",
"Nirwana",
"Nofretete",
"Nord",
"Normajean",
"Note this",
"Noteworthy",
"Nottingham",
"Novarra",
"Novene",
"Nueva Std",
"Nueva Std Cond",
"Nyala",
"Nymphe",
"NympheBold",
"NympheBoldItalic",
"NympheItalic",
"OCR A Extended",
"OCR A Std",
"OT-JTC淡斎草書「濃」",
"OT-JTC淡斎行書「彩」",
"OT-NIS-AYA",
"OT-NIS-KOI",
"Ocean Sans MM",
"Octavian",
"OctavianMT",
"OctavianMT Expert",
"OctavianMT Italic Expert",
"OctavianMT OsF Italic",
"OctavianMT SC",
"October",
"OdessaShadow",
"Oekumene",
"Offshore",
"OktaveBold",
"OktaveExtraBold",
"OktaveMedium",
"Old English Text MT",
"Old Style MT",
"Old Style MT Bold Outline",
"Olivia",
"Onedin",
"OnedinInline",
"OnedinOutline",
"Onyx",
"Onyx MT",
"Open Sans",
"OpenSymbol",
"Optima",
"Optima LT",
"Optima LT DemiBold",
"Optima LT ExtraBlack",
"Optima LT Medium",
"Orakel",
"Orator MN",
"Orator Std",
"Organda MN",
"Orinoco",
"Oriya MN",
"Oriya Sangam MN",
"OrlandoItalics",
"OrlandoRegular",
"Ornament",
"Orpheus",
"Ortem MN",
"Osaka",
"Ostara",
"Oswald",
"Outlaw",
"Outright Televism",
"Outsider",
"OutsiderOpen",
"PCMyungjo",
"PMingLiU",
"PMingLiU-ExtB",
"PT Mono",
"PT Sans",
"PT Sans Caption",
"PT Sans Narrow",
"PT Serif",
"PT Serif Caption",
"Pacific",
"PacificItalic",
"Pakenham",
"Palace",
"Palace Script",
"Palace Script MT",
"Palatino",
"Palatino Linotype",
"Palette",
"Palisander",
"PanamaBold",
"Pandero",
"Paneel",
"Papillon",
"Papyrus",
"Parabel",
"Paranoid",
"Parchment",
"Party LET",
"Parzifal",
"Pascal",
"Passion",
"Patras",
"Patrouille",
"Pauline",
"PaulineOpen",
"Peanuts",
"PeerGynt",
"PeerGyntItalic",
"Pegasus",
"Pelikan",
"PencilPete FONT",
"Penelope",
"Pepita MT",
"Perkeo",
"Perpetua",
"Perpetua MT",
"Perpetua Titling MT",
"PhaistosBold",
"PhaistosItalic",
"PhaistosRoman",
"Phantasia",
"Pharao",
"Philadelphia",
"Phoenix",
"Photina",
"Pianobar",
"Picobello",
"PilGi",
"Pinnoccio",
"Pirouette",
"Pittoresk",
"PixetlCondensed",
"PixetlHard",
"PixetlRegular",
"Placard MT",
"Plantagenet Cherokee",
"Plantin",
"Playbill",
"Playmate",
"Plinius",
"Polaris",
"Police",
"Poliphilus",
"Poliphilus Expert MT",
"Pollux",
"Pompadour",
"PompejiItalic",
"PompejiLight",
"PompejiRegular",
"Poor Richard",
"Pop",
"Poplar Std",
"Poppea",
"PortagoITC TT",
"Poussage",
"Praegnant",
"Prestige Elite Std",
"Preussen",
"Princetown LET",
"Priscilla",
"PriscillaBold",
"Pristina",
"Proxima Nova",
"Proxima Nova Alt",
"Proxima Nova ScOsf",
"Puppet",
"Puschkin",
"Quadriga",
"QuantumBoldCondensed",
"QuantumElongated",
"QuarterBold",
"QuarterMedium",
"QuarterOpen",
"QuartierBook",
"QuartierBookItalic",
"QuartierDemiBold",
"QueenBold",
"Quiberon",
"Quichotte",
"Quincy",
"Quinta",
"Quovadis",
"Raanana",
"Raavi",
"Racing",
"Rage Italic",
"Railing",
"Railroad",
"Rambla",
"RamonaInline",
"RamonaMedium",
"RangeBlack",
"RangeBold",
"RangeExtraBold",
"RangeLight",
"RangeMedium",
"Rapunzel",
"Rasant",
"Rasputin",
"Raveline",
"Ravie",
"Readers",
"Reformator",
"Relikt",
"Renault MN",
"Renegat",
"Rennes",
"ReportBold",
"ReportLight",
"Residenz",
"ResidenzOpen",
"Reykjavik",
"ReykjavikBold",
"ReykjavikFine",
"Rhapsodie",
"Rheingold",
"Rhodos",
"Ricarda",
"Richard",
"Riverboat",
"RobertoLight",
"Robespierre",
"Rockwell",
"Rockwell Condensed",
"Rockwell Extra Bold",
"Rococo Ornaments One MT",
"Rococo Ornaments Three MT",
"Rococo Ornaments Two MT",
"Rod",
"Roland",
"Romance",
"Romeo",
"RomeroBold",
"RomeroHeavy",
"RomeroLight",
"RomeroRegular",
"Romulus",
"Rondo MN",
"Rosewood Std",
"Rosewood Std Regular",
"Rosita",
"RotisSansSerif",
"Roundabout",
"Roxanne",
"Roxy",
"Rsfs10",
"Rsfs5",
"Rsfs7",
"Rubinstein",
"Ryohayu",
"S2GP月フォント",
"S2GP海フォント",
"S2Gうみフォント",
"S2G月フォント",
"SF Minced Meat",
"SF Minced Meat Extended",
"SF Minced Meat Shaded",
"SF Movie Poster",
"SF Movie Poster Condensed",
"SF New Republic",
"SF New Republic SC",
"SF Obliquities",
"SF Obliquities Extended",
"SF Obliquities Outline",
"SF Orson Casual Heavy",
"SF Orson Casual Light",
"SF Orson Casual Medium",
"SF Orson Casual Shaded",
"SF Pale Bottom",
"SF Pale Bottom Condensed",
"SF Pale Bottom Extended",
"SF Pale Bottom Shaded",
"SF Piezolectric",
"SF Piezolectric Condensed",
"SF Piezolectric Inline",
"SF Piezolectric SFX",
"SF Planetary Orbiter",
"SF Planetary Orbiter Outline",
"SF Port McKenzie",
"SF Port McKenzie Extended",
"SF Port McKenzie Outline",
"SF Proverbial Gothic",
"SF Proverbial Gothic Condensed",
"SF Proverbial Gothic Extended",
"SF Quartzite",
"SF Quartzite Extended",
"SF Quartzite Outline",
"SF RetroSplice",
"SF RetroSplice Condensed",
"SF RetroSplice Outline",
"SF RetroSplice SC",
"SF RetroSplice SC Condensed",
"SF RetroSplice SC Outline",
"SF RetroSplice SC Shaded",
"SF RetroSplice Shaded",
"SF Retroesque",
"SF Retroesque Outline",
"SF Retroesque SC",
"SF Scribbled Sans",
"SF Scribbled Sans SC",
"SF Shai Fontai",
"SF Shai Fontai Distressed",
"SF Shai Fontai Extended",
"SF Slapstick Comic",
"SF Slapstick Comic Shaded",
"SF Speakeasy",
"SF Speakeasy Outline",
"SF Speakeasy Shaded",
"SF Speedwaystar",
"SF Speedwaystar Condensed",
"SF Speedwaystar Shaded",
"SF Sports Night",
"SF Sports Night AltUpright",
"SF Sports Night Alternate",
"SF Sports Night NS",
"SF Sports Night NS AltUpright",
"SF Sports Night NS Alternate",
"SF Sports Night NS Upright",
"SF Sports Night Upright",
"SF Square Head",
"SF Square Head Condensed",
"SF Square Head Extended",
"SF Square Root",
"SF Square Root Extended",
"SF Square Root Shaded",
"SF Synthonic Pop",
"SF Synthonic Pop Condensed",
"SF Synthonic Pop Shaded",
"SF Tattle Tales",
"SF Tattle Tales Outline",
"SF Tattle Tales Shadow",
"SF Technodelight",
"SF Technodelight NS",
"SF Wasabi",
"SF Wasabi Condensed",
"SF Willamette",
"SF Willamette Extended",
"SF Wonder Comic",
"SF Wonder Comic Blotch",
"SF Wonder Comic Inline",
"SF Zero Gravity",
"SF Zero Gravity Condensed",
"STFangsong",
"STHeiti",
"STKaiti",
"STSong",
"Sachalin",
"Safran",
"SafranBold",
"SafranBoldItalic",
"SafranItalic",
"Sahara",
"Saigon",
"SaigonItalic",
"SaigonLight",
"Sakkal Majalla",
"Salinas",
"Saloon",
"Samurai",
"SanaFonKaku",
"Sandwich",
"Sanremo",
"Sansibar",
"Sanskrit 2003",
"Santa Fe LET",
"SarahLight",
"Sarajevo",
"Sarkophag",
"Saskatchewan",
"Sathu",
"Savanne",
"Savoye LET",
"Sayer Script MN",
"SayerSpiritual MN",
"ScalaSansOT",
"Scarlet",
"SchoolHouse Cursive B",
"SchoolHouse Printed A",
"Schulmeister",
"SciFly",
"Script Bold MT",
"Script MT Bold",
"Scriptina",
"Scriptina - Alternates",
"Scriptina Pro",
"Sea font",
"Sea font-pro",
"Segoe Print",
"Segoe Script",
"Segoe UI",
"Segoe UI Light",
"Segoe UI Semibold",
"Segoe UI Symbol",
"Sekunda",
"Selene",
"Senorita",
"Senussi",
"SeptemberBold",
"SeptemberBold Italic",
"SeptemberMedium",
"SeptemberMedium Italic",
"Septime",
"Sequester",
"Seravek",
"Sergeant SixPack",
"Serto Batnan",
"Serto Jerusalem",
"Serto Jerusalem Outline",
"Serto Kharput",
"Serto Malankara",
"Serto Mardin",
"Serto Urhoy",
"Seshat",
"Severus",
"Shadowone",
"Shamar",
"Sheffield",
"Sheriff",
"Sherwood",
"ShiltonExtended",
"ShiltonExtraBold",
"Shimano",
"Shimmy",
"Shonar Bangla",
"Shopping",
"Showcard Gothic",
"Shrewsbury",
"Shruti",
"Sierra",
"Signora",
"Silentina Film",
"Silentina Movie",
"Silom",
"Silver",
"SimHei",
"SimSun",
"SimSun-ExtB",
"Simone",
"SimpleLife",
"Simplified Arabic",
"Simplified Arabic Fixed",
"Sindbad",
"Sinfonia",
"Sinhala MN",
"Sinhala Sangam MN",
"Sinzano",
"Sirene",
"Sirius",
"Skelett",
"Sketch Rockwell",
"Skia",
"Skjoeld",
"SkylabCapsule",
"SkylabCode",
"SkylabRegular",
"Small Fonts",
"Smoking",
"Smyrna",
"Snap ITC",
"Snell Roundhand",
"Snoopy",
"Snowgoose",
"Snowgoose Back",
"Snowgoose Front",
"Soccer",
"Sommet",
"Songti SC",
"Songti TC",
"Soubrette",
"SoundBook",
"SoundLight",
"Source Sans Pro",
"Spaghetti",
"Sparta",
"Special Elite",
"Spirit",
"Splendid",
"Sports One MT",
"Sports Two MT",
"Spotka AlternateBlack",
"Spotka AlternateBlack Italic",
"Spotka AlternateBold",
"Spotka AlternateBold Italic",
"Spotka AlternateMedium",
"Spotka AlternateMedium Italic",
"Spotka AlternateRegular",
"Spotka AlternateRegular Italic",
"SpotkaBlack",
"SpotkaBlack Italic",
"SpotkaBlack SC",
"SpotkaBold",
"SpotkaBold Italic",
"SpotkaBold SC",
"SpotkaMedium",
"SpotkaMedium Italic",
"SpotkaMedium SC",
"SpotkaRegular",
"SpotkaRegular Italic",
"SpotkaRegular SC",
"Spotlight",
"Squash MN",
"Squawvalley",
"Stavanger",
"Steamer",
"Stencil",
"Stencil Antique MN",
"Stencil MN",
"Stencil Std",
"Sternschnuppe",
"Stettin",
"Stmary10",
"Stmary5",
"Stmary6",
"Stmary7",
"Stmary8",
"Stmary9",
"Stockholm",
"Stolzenfels",
"Stone Sans ITC TT",
"Stone Sans Sem ITC TT",
"Stonehenge",
"Stones",
"Stormy",
"Strangelove Next Wide",
"Strangelove Text",
"Strawberry",
"Street Soul",
"Strenuous 3D",
"Stromboli",
"Stuttgart",
"Stylistic",
"Suffolk",
"Sui Generis",
"Sui Generis Gaunt",
"Sui Generis Ink",
"SullyJonquieres MN",
"SullyJonquieresMN",
"SundanceKid",
"Sundsvall",
"SundsvallBold",
"SundsvallBoldItalic",
"SundsvallItalic",
"Sunflower",
"Sunset",
"Superclarendon",
"Surface",
"SurreyScript",
"Swaak Centennial MN",
"Swinger",
"Sylfaen",
"Sylvester",
"Symbol",
"Symbola",
"Synchro LET",
"System",
"TR Aardvark",
"TR Action Man",
"TR Aerial",
"TR Airmole",
"TR Airmole Shaded",
"TR Airmole Stripe",
"TR Alan Den",
"TR Albert",
"TR Alexei Copperplate",
"TR Algiers",
"TR Alpha Dance",
"TR AlphaMack",
"TR America",
"TR Anglican",
"TR Angostura Black",
"TR Another",
"TR Anyway",
"TR Arabia",
"TR Architecture",
"TR Ardour GM",
"TR Arial",
"TR Arial Black",
"TR Aristocrat",
"TR Arriba",
"TR Artistik",
"TR Astron Boy",
"TR Aswell",
"TR Atlantic Inline",
"TR Atomic",
"TR Augie",
"TR Avalon",
"TR Avatar",
"TR Baby Kruffy",
"TR Baez",
"TR Bahamas",
"TR Bahamas Light",
"TR BahamasHeavy",
"TR Bailey",
"TR Balcony Angels",
"TR Balloon",
"TR Baltar",
"TR Bandit",
"TR Banff",
"TR Bangkok",
"TR Bard",
"TR Batmos",
"TR Baveuse",
"TR Bedrock",
"TR Berylium",
"TR BitDust Two",
"TR Biting My Nails",
"TR Blue",
"TR Blue Highway",
"TR BobDylan",
"TR Bodnoff",
"TR Bolide",
"TR Book Antiqua",
"TR Bookman",
"TR Bookman ",
"TR Borneo",
"TR Briquet",
"TR Brisk",
"TR Brochure",
"TR Candice",
"TR CasperOpenFace",
"TR Cassia",
"TR Casual",
"TR Centurion Old",
"TR Century Gothic",
"TR Chaucer",
"TR Chinese Rocks",
"TR ChowMein",
"TR Clapton",
"TR Comic Sans MS",
"TR Cottage",
"TR Courier New",
"TR Cupertino",
"TR Dauphin",
"TR Dawn Castle",
"TR Deftone Stylus",
"TR Display Dots",
"TR Eagles",
"TR Eden Mills",
"TR Edmunds",
"TR Effloresce",
"TR Eight Track",
"TR Eklektic",
"TR Electroharmonix",
"TR Emboss",
"TR Enviro",
"TR Erie",
"TR Erie Contour",
"TR ErieBlack",
"TR ErieLight",
"TR Expo",
"TR Eye Rhyme",
"TR Field Day Filter",
"TR Firenze",
"TR Floyd",
"TR France",
"TR Frankenstein",
"TR FrankfurtGothicHeavy",
"TR Frankfurter Hlt",
"TR Freehand575",
"TR Freehand591",
"TR Freeport",
"TR Freestyle Script",
"TR Fujiyama",
"TR Galleria",
"TR Goodfish",
"TR Harlow",
"TR Harpoon",
"TR HendrixBlack",
"TR Homeward Bound",
"TR Honda",
"TR Impact",
"TR International Chunkfunk",
"TR Jupiter",
"TR Kabel Bd",
"TR Kastler",
"TR Keypunch",
"TR Kids",
"TR Kimberley",
"TR Koala",
"TR LCD",
"TR Larabiefont",
"TR Lincoln",
"TR Linus",
"TR Lithograph",
"TR Living by Numbers",
"TR Lockergnome",
"TR Lucida Handwriting",
"TR Lucida Sans",
"TR Lucida Sans Unicode",
"TR Matisse ITC",
"TR McLaughlin",
"TR McLean",
"TR Memorandum",
"TR MonaLisa Recut",
"TR Motor",
"TR Mystical",
"TR Nasalization",
"TR Oregon",
"TR Palette",
"TR Paradise",
"TR Paragon",
"TR Penguin",
"TR Pepper",
"TR Pipeline",
"TR Plaza",
"TR President",
"TR Princetown",
"TR ProseAntique",
"TR Pump Triline",
"TR Queen",
"TR Quicksilver",
"TR QuillScript",
"TR Renfrew",
"TR Schubert",
"TR Shogun",
"TR Tahoma",
"TR Tahoma Bold",
"TR Tempus Sans ITC",
"TR Times New Roman",
"TR Verdana",
"TR Verdana Bold",
"TRAllegro",
"TSIB",
"TSIL",
"TT-NIS-ARAS",
"TT-新井篆書S",
"Tableau",
"Tahoma",
"Taille",
"Taipeh",
"Tambourin",
"Tamil MN",
"Tamil Sangam MN",
"Tank",
"Tank Lite",
"Tarantel",
"TaskBold",
"TaskBold Italic",
"TaskBook",
"TaskDouble",
"TaskHairy",
"TaskItalic",
"TaskOpen",
"TaskSmall Caps",
"TaskToobig",
"Tastatur",
"Taurus",
"TeX Gyre Adventor",
"TeX Gyre Bonum",
"TeX Gyre Chorus",
"TeX Gyre Cursor",
"TeX Gyre Heros",
"TeX Gyre Heros Cn",
"TeX Gyre Pagella",
"TeX Gyre Schola",
"TeX Gyre Termes",
"TeX copti",
"TeX copto",
"TeX feybl10",
"TeX feybo10",
"TeX feybr10",
"TeX feyml10",
"TeX feymo10",
"TeX feymr10",
"TeX040feybl10",
"TeX040feybo10",
"TeX040feybr10",
"TeX040feyml10",
"TeX040feymo10",
"TeX040feymr10",
"Teardrops",
"Techno",
"TechnoBold",
"TechnoInline",
"Tedeum",
"Tedeus",
"Tekton Pro",
"Tekton Pro Cond",
"Tekton Pro Ext",
"Telegraphic",
"Telegraphic Light",
"Telepath",
"TelepathOpen",
"Telescope",
"Telugu MN",
"Telugu Sangam MN",
"Tempo",
"Tempus Sans ITC",
"Tenby Five",
"Tentakel",
"TentakelOpen",
"Terminal",
"Teutonia",
"Texarkana",
"The King & Queen font",
"The Sans Black-",
"The Sans Bold-",
"The Sans Extra Bold-",
"The Sans Extra Light-",
"The Sans Light-",
"The Sans Semi Bold-",
"The Sans Semi Light-",
"The Sans-",
"The Serif Black-",
"The Serif Bold-",
"The Serif Extra Bold-",
"The Serif Extra Light-",
"The Serif Light-",
"The Serif Semi Bold-",
"The Serif Semi Light-",
"The Serif-",
"TheklaBoldExtended",
"TheklaExtended",
"TheodorInitials",
"Thonburi",
"Tiberius",
"Tiffany",
"Times",
"Times New Roman",
"Tintagel",
"Tisa Pro",
"Tivoli",
"Tombola",
"Tombstone",
"Topeka",
"Torino",
"Tornado",
"Trabant",
"TrabantBold",
"TradeGothic",
"TradeGothic LT",
"TradeGothic LT Bold",
"TradeGothic LT CondEighteen",
"TradeGothic LT Extended",
"TradeGothic LT Light",
"TradeGothicMacron",
"Traditional Arabic",
"Trajan",
"Trajan Pro",
"Transvestit",
"Trashco",
"Traveling _Typewriter",
"Treasure",
"Trebuchet MS",
"Triathlon",
"Tribune",
"Triplex",
"TriplexBold",
"TriplexCondBlack",
"TriplexCondRegular",
"TriplexExtrabold",
"TriplexItalicBold",
"TriplexItalicExtrabold",
"TriplexItalicLight",
"Tripoli",
"TripoliBold",
"Trondheim",
"Tropical",
"TropicalOpen",
"Troubadour",
"Truesdell",
"TruesdellAlternate",
"TruesdellSorts",
"Tshirt",
"Tuesday",
"Tundra",
"Tunga",
"Turnier",
"Tw Cen MT",
"Tw Cen MT Condensed",
"Tw Cen MT Condensed Extra Bold",
"Two Turtle Doves",
"Type Embellishments One LET",
"Typenrad",
"TypenradBold",
"TypenradBoldItalic",
"TypenradItalic",
"TypenradSpecial",
"TypenradSpecialBold",
"Typeshop",
"Typewriter MT",
"Typodermic",
"Tzigane MN",
"URW Bookman L",
"URW Chancery L",
"URW Gothic L",
"URW Palladio L",
"Ulster",
"Ume Gothic",
"Ume Gothic C4",
"Ume Gothic C5",
"Ume Gothic O5",
"Ume Gothic S4",
"Ume Gothic S5",
"Ume Mincho",
"Ume Mincho S3",
"Ume P Gothic",
"Ume P Gothic C4",
"Ume P Gothic C5",
"Ume P Gothic O5",
"Ume P Gothic S4",
"Ume P Gothic S5",
"Ume P Mincho",
"Ume P Mincho S3",
"Ume UI Gothic",
"Ume UI Gothic O5",
"Unclesam",
"Undertaker",
"Undine",
"Unibody 8",
"Unikum",
"UnikumOpen",
"UnionPacificBlack",
"Univers",
"Univers-Light",
"Univers-Medium",
"Univers-ThinUltraCn",
"Univers-CondensedLt",
"Univers-LightUltraCn",
"Univers-Extended",
"Univers-Condensed",
"Univers-UltraCondensed",
"Univers-BoldItalic",
"Univers-BlackExtended",
"Univers-ExtraBlack",
"Univers-ExtraBlackEx",
"Uranus",
"UranusBold",
"Utopia",
"Utrecht",
"Utsaah",
"VAG Rounded",
"Valence",
"Valerie",
"ValerieCapitale",
"Vampir",
"VampirBold",
"VampirOutline",
"Van Dijck",
"Vanadin",
"Vani",
"Vatikan",
"Veilchen",
"Velvet",
"Venezia",
"VenusGothicBold",
"Verdana",
"Verdun",
"Viaduct",
"Viant MN",
"Victoria",
"Vignette",
"Vijaya",
"Village",
"Vinegar",
"Viner Hand ITC",
"Vineta",
"Violett",
"Violine",
"Virgin",
"Vivaldi",
"Vivaldi MN",
"Vivian",
"Vladimir Script",
"Volkhov",
"VolkswagenOutline",
"Vongole",
"Vosges",
"VosgesDemiBold",
"Vrinda",
"Walbaum MT",
"Walburga",
"Walpurgis",
"Walzer",
"Wanted",
"Warehouse",
"Warszawa",
"Wartburg",
"Washington",
"WatakushiFont",
"Watch MN",
"Wawati SC",
"Wawati TC",
"Webdings",
"Wedgewood",
"Weibei SC",
"Weibei TC",
"Weimar",
"Wellington",
"Wenceslas",
"Westend",
"Western",
"Westgothic",
"Whitesnake",
"Wide Latin",
"Windsor MN",
"WindsorSword",
"Wingdings",
"Wingdings 2",
"Wingdings 3",
"Winner",
"Winnie the Hoop",
"Winston",
"Witchdoctor",
"Wolfgang",
"Woodstock",
"Wyattearp",
"XYATIP",
"XYBSQL",
"XYBTIP",
"XYCIRC",
"XYCMAT",
"XYCMBT",
"XYDASH",
"XYEUAT",
"XYEUBT",
"XYLUAT",
"XYLUBT",
"Xanadu",
"Xanten",
"Xanthippe",
"XenonBold",
"XenonMedium",
"Xerxes",
"Xingkai SC",
"Yankee",
"Ypsilon",
"YuGothic",
"YuMincho",
"Yuanti SC",
"Yuppy SC",
"Yuppy TC",
"ZWAdobeF",
"Zaandam",
"Zalderdash",
"Zambesi MN",
"Zapf Dingbats",
"Zapfino",
"Zartbitter",
"Zeitgeist MT",
"Zekton Free",
"Zeppelin",
"Zud Juice",
"Zupiter",
"Zurich",
"Zyankali",
"Zyklop",
"ZyklopInline",
"Zylinder",
"Zypresse",
"あくあフォント",
"あずきフォント",
"えれーな",
"きろ字",
"さなフォン角",
"ふい字",
"へた字",
"まきばフォント",
"みかちゃん",
"みかちゃん-P",
"みかちゃん-PB",
"みかちゃん-PS",
"りょは～ゆ",
"アームドレモン",
"カクカク太字1",
"ダサ字",
"ダメ字",
"ヒラギノ丸ゴ Pro",
"ヒラギノ丸ゴ Pro W4",
"ヒラギノ丸ゴ ProN",
"ヒラギノ丸ゴ ProN W4",
"ヒラギノ明朝 Pro",
"ヒラギノ明朝 Pro W3",
"ヒラギノ明朝 Pro W6",
"ヒラギノ明朝 ProN",
"ヒラギノ明朝 ProN W3",
"ヒラギノ明朝 ProN W6",
"ヒラギノ角ゴ Pro",
"ヒラギノ角ゴ Pro W3",
"ヒラギノ角ゴ Pro W6",
"ヒラギノ角ゴ ProN",
"ヒラギノ角ゴ ProN W3",
"ヒラギノ角ゴ ProN W6",
"ヒラギノ角ゴ Std",
"ヒラギノ角ゴ Std W8",
"ヒラギノ角ゴ StdN",
"ヒラギノ角ゴ StdN W8",
"ホリデイMDJP02",
"メイリオ",
"仿宋",
"宋体",
"小塚ゴシック Pro",
"小塚ゴシック Pro B",
"小塚ゴシック Pro EL",
"小塚ゴシック Pro H",
"小塚ゴシック Pro L",
"小塚ゴシック Pro M",
"小塚ゴシック Pro R",
"小塚明朝 Pro",
"小塚明朝 Pro B",
"小塚明朝 Pro EL",
"小塚明朝 Pro H",
"小塚明朝 Pro L",
"小塚明朝 Pro M",
"小塚明朝 Pro R",
"微軟正黑體",
"微软雅黑",
"手書き文字",
"新宋体",
"新細明體",
"新細明體-ExtB",
"有澤楷書",
"有澤行書",
"梅Pゴシック",
"梅PゴシックC4",
"梅PゴシックC5",
"梅PゴシックO5",
"梅PゴシックS4",
"梅PゴシックS5",
"梅P明朝",
"梅P明朝S3",
"梅UIゴシック",
"梅UIゴシックO5",
"梅ゴシック",
"梅ゴシックC4",
"梅ゴシックC5",
"梅ゴシックO5",
"梅ゴシックS4",
"梅ゴシックS5",
"梅明朝",
"梅明朝S3",
"楷体",
"標楷體",
"白舟印相体教漢",
"白舟古印体教漢",
"白舟極太楷書教漢",
"白舟楷書教漢",
"白舟正行書教漢",
"白舟篆古印教漢",
"白舟篆書教漢",
"白舟草書教漢",
"白舟行書教漢",
"白舟隷書教漢",
"私たん",
"細明體",
"細明體-ExtB",
"細明體_HKSCS",
"細明體_HKSCS-ExtB",
"花園明朝",
"衡山毛筆フォント",
"衡山毛筆フォント草書",
"衡山毛筆フォント行書",
"誠印相太",
"誠印相細",
"青柳疎石フォント2",
"青柳衡山フォントT",
"青柳衡山フォント草書２",
"魚石行書",
"黑体",
"黑体-简",
"黑体-繁",
"黑體-簡",
"黑體-繁",
"黒体-簡",
"黒体-繁",
"굴림",
"굴림체",
"궁서",
"궁서체",
"돋움",
"돋움체",
"맑은 고딕",
"바탕",
"바탕체",
"ＡＲ黒丸ＰＯＰ体Ｈ",
"ＡＲＰ黒丸ＰＯＰ体Ｈ",
"ＤＦPOPコンW12",
"ＤＦPOP体",
"ＤＦクラフト遊W7",
"ＤＦブラッシュＲＤW12",
"ＤＦブラッシュＳＱW12",
"ＤＦ康印体W4",
"ＤＦ極太ゴシック体",
"ＤＦ極太丸ゴシック体",
"ＤＦ極太明朝体",
"ＤＦ流隷体W5",
"ＤＦ特太ゴシック体",
"ＤＦ超極太丸ゴシック体",
"ＤＦ超極太楷書体",
"ＤＦ風雲体W12",
"ＤＦ麗雅宋",
"ＤＦＧPOPコンW12",
"ＤＦＧクラフト遊W7",
"ＤＦＧブラッシュＲＤW12",
"ＤＦＧブラッシュＳＱW12",
"ＤＦＧ康印体W4",
"ＤＦＧ極太ゴシック体",
"ＤＦＧ極太丸ゴシック体",
"ＤＦＧ極太明朝体",
"ＤＦＧ流隷体W5",
"ＤＦＧ超極太丸ゴシック体",
"ＤＦＧ超極太楷書体",
"ＤＦＧ風雲体W12",
"ＤＦＧ麗雅宋",
"ＤＦＰPOPコンW12",
"ＤＦＰPOP体",
"ＤＦＰクラフト遊W7",
"ＤＦＰブラッシュＲＤW12",
"ＤＦＰブラッシュＳＱW12",
"ＤＦＰ極太ゴシック体",
"ＤＦＰ極太丸ゴシック体",
"ＤＦＰ極太明朝体",
"ＤＦＰ特太ゴシック体",
"ＤＦＰ超極太丸ゴシック体",
"ＤＦＰ超極太楷書体",
"ＤＦＰ風雲体W12",
"ＤＦＰ麗雅宋",
"ＦＡ ゴシックＢ",
"ＦＡ ポップＢ",
"ＦＡ 丸ゴシックＭ",
"ＦＡ 教科書Ｍ",
"ＦＡ 瑞筆行書Ｍ",
"ＦＡ 隷書Ｍ",
"ＨＧｺﾞｼｯｸE-PRO",
"ＭＳ ゴシック",
"ＭＳ 明朝",
"ＭＳ Ｐゴシック",
"ＭＳ Ｐ明朝",
"ＭＳ ＰＲゴシック"
];
